"""empty message

Revision ID: c656bd98cfb6
Revises: a94c106be995
Create Date: 2022-07-28 15:54:57.724983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c656bd98cfb6'
down_revision = 'a94c106be995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=220),
               nullable=False)
    op.alter_column('user', 'zip_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=220),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'zip_code',
               existing_type=sa.String(length=220),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=220),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
